COMPANY_TICKER_ALIASES: dict[str, str] = {
    "3m": "MMM",
    "abbott": "ABT",
    "abbott laboratories": "ABT",
    "abbvie": "ABBV",
    "adobe": "ADBE",
    "advanced micro devices": "AMD",
    "airbnb": "ABNB",
    "alibaba": "BABA",
    "alphabet": "GOOGL",
    "amazon": "AMZN",
    "amazon web services": "AMZN",
    "amd": "AMD",
    "american express": "AXP",
    "amgen": "AMGN",
    "apple": "AAPL",
    "applied materials": "AMAT",
    "arm": "ARM",
    "arm holdings": "ARM",
    "astrazeneca": "AZN",
    "atlassian": "TEAM",
    "baidu": "BIDU",
    "bank of america": "BAC",
    "berkshire hathaway": "BRK.B",
    "blackrock": "BLK",
    "blackstone": "BX",
    "boeing": "BA",
    "booking": "BKNG",
    "booking holdings": "BKNG",
    "broadcom": "AVGO",
    "byd": "BYDDY",
    "caterpillar": "CAT",
    "charles schwab": "SCHW",
    "chevron": "CVX",
    "chipotle": "CMG",
    "cisco": "CSCO",
    "citigroup": "C",
    "cloudflare": "NET",
    "coca-cola": "KO",
    "coinbase": "COIN",
    "conocophillips": "COP",
    "costco": "COST",
    "crowdstrike": "CRWD",
    "datadog": "DDOG",
    "deere": "DE",
    "disney": "DIS",
    "duke energy": "DUK",
    "eli lilly": "LLY",
    "estee lauder": "EL",
    "exxon": "XOM",
    "exxon mobil": "XOM",
    "ford": "F",
    "freeport-mcmoran": "FCX",
    "general electric": "GE",
    "general motors": "GM",
    "gilead": "GILD",
    "gilead sciences": "GILD",
    "goldman sachs": "GS",
    "google": "GOOGL",
    "home depot": "HD",
    "honeywell": "HON",
    "ibm": "IBM",
    "intel": "INTC",
    "intuit": "INTU",
    "intuitive surgical": "ISRG",
    "jd.com": "JD",
    "johnson & johnson": "JNJ",
    "johnson and johnson": "JNJ",
    "jpmorgan": "JPM",
    "jpmorgan chase": "JPM",
    "kla": "KLAC",
    "lam research": "LRCX",
    "li auto": "LI",
    "linde": "LIN",
    "lockheed martin": "LMT",
    "lowe's": "LOW",
    "lululemon": "LULU",
    "mastercard": "MA",
    "mcdonald's": "MCD",
    "meta": "META",
    "micron": "MU",
    "microsoft": "MSFT",
    "moderna": "MRNA",
    "mongodb": "MDB",
    "morgan stanley": "MS",
    "netflix": "NFLX",
    "netease": "NTES",
    "newmont": "NEM",
    "nextera energy": "NEE",
    "nio": "NIO",
    "nike": "NKE",
    "northrop grumman": "NOC",
    "novo nordisk": "NVO",
    "nvidia": "NVDA",
    "occidental petroleum": "OXY",
    "oracle": "ORCL",
    "palantir": "PLTR",
    "palo alto networks": "PANW",
    "paypal": "PYPL",
    "pdd": "PDD",
    "pdd holdings": "PDD",
    "pepsico": "PEP",
    "pfizer": "PFE",
    "procter & gamble": "PG",
    "qualcomm": "QCOM",
    "regeneron": "REGN",
    "rivian": "RIVN",
    "rtx": "RTX",
    "salesforce": "CRM",
    "sap": "SAP",
    "schlumberger": "SLB",
    "servicenow": "NOW",
    "shopify": "SHOP",
    "snowflake": "SNOW",
    "sofi": "SOFI",
    "starbucks": "SBUX",
    "taiwan semiconductor": "TSM",
    "target": "TGT",
    "tencent": "TCEHY",
    "tesla": "TSLA",
    "texas instruments": "TXN",
    "thermo fisher": "TMO",
    "tsmc": "TSM",
    "uber": "UBER",
    "unitedhealth": "UNH",
    "unitedhealth group": "UNH",
    "visa": "V",
    "walmart": "WMT",
    "wells fargo": "WFC",
    "xpeng": "XPEV",
    "zscaler": "ZS",
}


TOPIC_ETF_ALIASES: dict[str, list[str]] = {
    "ai": ["QQQ", "SMH"],
    "artificial intelligence": ["QQQ", "SMH"],
    "bank": ["XLF"],
    "banks": ["XLF"],
    "biotech": ["XLV"],
    "cloud": ["QQQ"],
    "energy": ["XLE"],
    "gold": ["GLD"],
    "healthcare": ["XLV"],
    "oil": ["XLE", "USO"],
    "semiconductor": ["SMH", "SOXX"],
    "software": ["QQQ"],
    "treasury": ["TLT"],
}

SECTOR_PEERS: dict[str, dict[str, list[str]]] = {
    "NVDA": {"related": ["AMD", "TSM", "INTC", "AVGO"], "etfs": ["SMH", "SOXX", "QQQ"]},
    "AMD": {"related": ["NVDA", "TSM", "INTC"], "etfs": ["SMH", "SOXX"]},
    "INTC": {"related": ["NVDA", "AMD", "TSM"], "etfs": ["SMH", "SOXX"]},
    "AVGO": {"related": ["NVDA", "QCOM"], "etfs": ["SMH", "SOXX"]},
    "TSM": {"related": ["NVDA", "AMD", "INTC", "ASML"], "etfs": ["SMH", "SOXX"]},
    "ASML": {"related": ["TSM", "AMAT", "LRCX"], "etfs": ["SMH", "SOXX"]},
    "QCOM": {"related": ["AVGO", "AMD", "INTC"], "etfs": ["SMH", "SOXX"]},
    "MU": {"related": ["NVDA", "AMD", "TSM"], "etfs": ["SMH"]},
    "AMAT": {"related": ["LRCX", "KLAC", "ASML"], "etfs": ["SMH"]},
    "LRCX": {"related": ["AMAT", "KLAC", "ASML"], "etfs": ["SMH"]},
    "KLAC": {"related": ["AMAT", "LRCX"], "etfs": ["SMH"]},
    "TSLA": {"related": ["GM", "F", "RIVN"], "etfs": ["ARKK", "QQQ"]},
    "GM": {"related": ["TSLA", "F"], "etfs": []},
    "F": {"related": ["TSLA", "GM"], "etfs": []},
    "RIVN": {"related": ["TSLA"], "etfs": []},
    "MSFT": {"related": ["GOOGL", "AMZN", "ORCL"], "etfs": ["QQQ"]},
    "GOOGL": {"related": ["MSFT", "AMZN", "META"], "etfs": ["QQQ"]},
    "AMZN": {"related": ["MSFT", "GOOGL"], "etfs": ["QQQ"]},
    "META": {"related": ["GOOGL"], "etfs": ["QQQ"]},
    "AAPL": {"related": ["MSFT", "GOOGL"], "etfs": ["QQQ"]},
    "NFLX": {"related": ["DIS"], "etfs": ["QQQ"]},
    "JPM": {"related": ["BAC", "GS", "MS", "WFC", "C"], "etfs": ["XLF"]},
    "BAC": {"related": ["JPM", "GS", "WFC", "C"], "etfs": ["XLF"]},
    "GS": {"related": ["JPM", "MS", "BAC"], "etfs": ["XLF"]},
    "MS": {"related": ["JPM", "GS"], "etfs": ["XLF"]},
    "WFC": {"related": ["JPM", "BAC", "C"], "etfs": ["XLF"]},
    "C": {"related": ["JPM", "BAC", "WFC"], "etfs": ["XLF"]},
    "XOM": {"related": ["CVX", "COP", "OXY"], "etfs": ["XLE"]},
    "CVX": {"related": ["XOM", "COP"], "etfs": ["XLE"]},
    "COP": {"related": ["XOM", "CVX"], "etfs": ["XLE"]},
    "LLY": {"related": ["UNH", "JNJ", "PFE", "MRK"], "etfs": ["XLV"]},
    "UNH": {"related": ["LLY", "JNJ", "PFE"], "etfs": ["XLV"]},
    "JNJ": {"related": ["LLY", "PFE", "MRK"], "etfs": ["XLV"]},
    "PFE": {"related": ["LLY", "MRK", "MRNA"], "etfs": ["XLV"]},
    "MRK": {"related": ["LLY", "PFE"], "etfs": ["XLV"]},
    "WMT": {"related": ["COST", "TGT", "HD"], "etfs": ["XLY"]},
    "COST": {"related": ["WMT", "TGT"], "etfs": ["XLY"]},
    "HD": {"related": ["LOW", "WMT"], "etfs": ["XLY"]},
    "BA": {"related": ["GE", "RTX", "LMT", "NOC"], "etfs": ["ITA"]},
    "GE": {"related": ["BA", "RTX", "HON"], "etfs": ["ITA"]},
    "RTX": {"related": ["BA", "LMT", "NOC"], "etfs": ["ITA"]},
    "LMT": {"related": ["BA", "RTX", "NOC"], "etfs": ["ITA"]},
    "PLTR": {"related": ["CRM", "NOW", "MSFT"], "etfs": ["QQQ"]},
    "CRM": {"related": ["NOW", "ADBE", "ORCL", "MSFT"], "etfs": ["QQQ"]},
    "NOW": {"related": ["CRM", "ADBE"], "etfs": ["QQQ"]},
    "ADBE": {"related": ["CRM", "NOW", "MSFT"], "etfs": ["QQQ"]},
    "ORCL": {"related": ["MSFT", "CRM", "SAP"], "etfs": ["QQQ"]},
    "UBER": {"related": ["TSLA"], "etfs": []},
    "SHOP": {"related": ["AMZN", "WMT"], "etfs": ["QQQ"]},
    "PYPL": {"related": ["V", "MA", "SQ"], "etfs": ["XLF"]},
    "V": {"related": ["MA", "PYPL"], "etfs": ["XLF"]},
    "MA": {"related": ["V", "PYPL"], "etfs": ["XLF"]},
    "COIN": {"related": ["PYPL"], "etfs": []},
    "DIS": {"related": ["NFLX"], "etfs": ["QQQ"]},
    "NKE": {"related": ["LULU", "SBUX"], "etfs": ["XLY"]},
    "SBUX": {"related": ["MCD", "NKE"], "etfs": ["XLY"]},
    "MCD": {"related": ["SBUX", "CMG"], "etfs": ["XLY"]},
    "CAT": {"related": ["DE", "GE"], "etfs": ["XLI"]},
    "DE": {"related": ["CAT"], "etfs": ["XLI"]},
    "HON": {"related": ["GE", "BA", "RTX"], "etfs": ["XLI", "ITA"]},
    "TXN": {"related": ["QCOM", "INTC"], "etfs": ["SMH"]},
    "BABA": {"related": ["JD", "PDD", "TCEHY"], "etfs": ["MCHI"]},
    "JD": {"related": ["BABA", "PDD"], "etfs": ["MCHI"]},
    "PDD": {"related": ["BABA", "JD"], "etfs": ["MCHI"]},
    "TCEHY": {"related": ["BABA"], "etfs": ["MCHI"]},
    "BIDU": {"related": ["BABA", "TCEHY"], "etfs": ["MCHI"]},
    "NIO": {"related": ["TSLA", "XPEV", "LI"], "etfs": ["ARKK"]},
    "XPEV": {"related": ["TSLA", "NIO", "LI"], "etfs": []},
    "LI": {"related": ["TSLA", "NIO", "XPEV"], "etfs": []},
    "CRWD": {"related": ["PANW", "ZS", "NET"], "etfs": ["QQQ"]},
    "PANW": {"related": ["CRWD", "ZS", "NET"], "etfs": ["QQQ"]},
    "ZS": {"related": ["CRWD", "PANW", "NET"], "etfs": ["QQQ"]},
    "NET": {"related": ["CRWD", "ZS", "DDOG"], "etfs": ["QQQ"]},
    "DDOG": {"related": ["NET", "SNOW", "MDB"], "etfs": ["QQQ"]},
    "SNOW": {"related": ["DDOG", "MDB"], "etfs": ["QQQ"]},
    "MDB": {"related": ["SNOW", "DDOG"], "etfs": ["QQQ"]},
    "TEAM": {"related": ["CRM", "NOW"], "etfs": ["QQQ"]},
    "SAP": {"related": ["ORCL", "MSFT", "CRM"], "etfs": []},
    "IBM": {"related": ["ORCL", "MSFT"], "etfs": ["QQQ"]},
    "CSCO": {"related": [], "etfs": []},
    "INTU": {"related": ["CRM", "ADBE"], "etfs": ["QQQ"]},
    "ARM": {"related": ["NVDA", "AMD", "TSM", "QCOM"], "etfs": ["SMH"]},
}


def get_sector_peers(ticker: str) -> tuple[list[str], list[str]]:
    entry = SECTOR_PEERS.get(ticker.upper(), {})
    return list(entry.get("related", [])), list(entry.get("etfs", []))


def map_companies_to_tickers(companies: list[str]) -> list[str]:
    result: list[str] = []
    for company in companies:
        key = _normalize_alias(company)
        ticker = COMPANY_TICKER_ALIASES.get(key)
        if ticker:
            result.append(ticker)
    return _dedupe(result)


def map_topics_to_etfs(topics: list[str]) -> list[str]:
    result: list[str] = []
    for topic in topics:
        key = _normalize_alias(topic)
        for alias, etfs in TOPIC_ETF_ALIASES.items():
            if alias in key:
                result.extend(etfs)
    return _dedupe(result)


def _normalize_alias(value: str) -> str:
    return " ".join(str(value or "").strip().lower().replace(",", " ").split())


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        text = item.strip().upper()
        if text and text not in seen:
            seen.add(text)
            result.append(text)
    return result
